### ISSUE TITLE
Error when open "Provisioned Apps" tab 

### ISSUE THREAD

**Issue by WNantes** [ConditionalException/Windows10Privacy#1]
Every time I try to open the "Provisioned Apps" tab, I receive this error:
![image](https://user-images.githubusercontent.com/53318529/61911261-f5cb9280-af04-11e9-8159-6f6c8fe38579.png)

An untreated exception has occurred in the application.
...

The request is not supported.

The content of this windows shows this text:
"
************** Texto de Exceção **************
System.Management.Automation.CmdletInvocationException: Não há suporte para o pedido.
 ---> System.Runtime.InteropServices.COMException: Não há suporte para o pedido.

   em System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   em System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   em System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   em System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   em System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   em System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   em System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   em WindowsFormsApp1.MainForm.btnPRefresh_Click(Object sender, EventArgs e)
   em WindowsFormsApp1.MainForm.ProvisionedApps_Enter(Object sender, EventArgs e)
   em System.Windows.Forms.Control.OnEnter(EventArgs e)
   em System.Windows.Forms.TabPage.OnEnter(EventArgs e)
   em System.Windows.Forms.TabPage.FireEnter(EventArgs e)
   em System.Windows.Forms.TabControl.OnSelected(TabControlEventArgs e)
   em System.Windows.Forms.TabControl.WmSelChange()
   em System.Windows.Forms.TabControl.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
"

The Windows info is:
Windows 10 Pro
Version 1903
Compilation 18362.239

Next, the app closes.

**Comment by ConditionalException** [comment]
Hey there! I'm really sorry about not responding until now. Unfortunately I really haven't taken the time to redo the project how I like (and apparently GitHub doesn't notify me of issue reports), but for curiosity sake, if you still have this issue could you try running a command in an elevated powershell and letting me know what results you get?

Open a PowerShell window by searching for powershell in the start menu, right click on powershell and click "Run as administrator"

The command I want you to run is:
`Get-AppxProvisionedPackage -Online`

That's really all that just opening that tab does, so if you don't have proper permissions when you start the application then it could throw an exception (because I did a poor job of checking for errors)
